title:            clokwork.net
tagline:          Code - Physics - Analysis
description:      Describe your website.
canonical:        http://clokwork.net

# Owner/author information
owner:
  name:           Derek Smith
  avatar:         mechwarrior.jpg
  bio:            "Code. Physics. Analysis."
  email:          derek@clokwork.net
  twitter:        cloksmith
  github:         clok
  instagram:      clokwork
  location:       "Austin, TX"
  # Plug in your disqus shortname!

tools:
  standards:      "HTML, SCSS, Jekyll"
  software:       "git"

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about
  - title: Github
    url: https://github.com/clok
    external: true
  - title: Twitter
    url: https://twitter.com/cloksmith
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Chicago
future:      true
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  input: GFM
  syntax_highlighter: rouge

sass:
  style: :compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Gemfile.lock", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]
